PanaderiaElMana/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('apps.usuarios.urls', namespace='usuarios')),
    path('pedidos/', include('apps.pedidos.urls', namespace='pedidos')),
    path('ventas/', include('apps.ventas.urls', namespace='ventas')),
    path('productos/', include('apps.productos.urls', namespace='productos')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/ventas/urls.py
from django.urls import path
from apps.ventas import views 

app_name = 'ventas'
urlpatterns = [
    path('', views.registroVentas, name='registro_ventas'),
    path('informe/', views.informeVentas, name="informe_ventas"),
    path('crearMayorista/', views.registroMayoristas, name="registro_mayoristas"),
    path("informe/<int:id>", views.detalleVenta, name="detalle_venta"),
    path("anular/<int:id>", views.anularVenta, name="anular_venta"),
    path("informe/mayoristas/", views.informeMayoristas, name="informe_mayoristas"),
    path("informe/mayoristas/darBaja/<int:cuit>", views.darDeBajaMayorista, name="baja_mayorista"),
    path("informe/mayoristas/<int:cuit>", views.modificarMayorista, name='modificar_mayorista'),
    path("informe/mayoristas/detalles/<int:cuit>", views.detallesMayorista, name="detalles_mayorista"),
    path('informe_ventas_pdf/', views.generar_informe_pdf, name='informe_ventas_pdf')
]

apps/ventas/models.py
from django.db import models
from django.core.validators import MinValueValidator
from apps.productos.models import Producto
from apps.usuarios.models import Usuario
# Create your models here.

class Mayorista(models.Model):
    cuit= models.CharField(max_length=11,primary_key=True)
    razon_social=models.CharField(max_length=20)
    direccion= models.TextField(max_length=50)
    telefono= models.CharField(max_length=20)
    email= models.CharField(max_length=50)
    estado=models.BooleanField(default=True)
    CONDICION_VENTA_CHOICES = [
        ('CONTADO', 'Contado'),  # Primer valor es el que se guarda en la BD, el segundo es el que se muestra
        ('CREDITO', 'Credito'),  
    ]
    condicion_venta= models.CharField(max_length=15, choices=CONDICION_VENTA_CHOICES)
    def __str__(self):
        return self.razon_social

class Venta(models.Model):
    numeroComprobante= models.CharField(max_length=15)
    FechaVenta= models.DateField()
    precioTotal= models.FloatField(validators=[MinValueValidator(0.0)])
    observaciones= models.TextField(max_length=200)                        
    estado=models.BooleanField(default=True)

    TIPO_COMPROBANTE_CHOICES = [
        ('RECIBO', 'Recibo'),  # Primer valor es el que se guarda en la BD, el segundo es el que se muestra
        ('FACTURA', 'Factura'),
        ('OTRO', 'Otro')
        
    ]
    FORMA_PAGO_CHOICES = [
        ('CONTADO', 'Contado'),  # Primer valor es el que se guarda en la BD, el segundo es el que se muestra
        ('TRANSFERENCIA', 'Transferencia'),
        ('CREDITO', 'Credito'),
        ('OTRO', 'Otro')
        
    ]
    tipo_venta = models.CharField(max_length=15)
    tipo_comprobante = models.CharField(max_length=15, choices=TIPO_COMPROBANTE_CHOICES)
    forma_pago = models.CharField(max_length=15, choices=FORMA_PAGO_CHOICES)
    

    

class ItemProducto(models.Model):
    venta= models.ForeignKey(Venta,on_delete=models.CASCADE)
    producto= models.ForeignKey(Producto,on_delete=models.CASCADE)
    cantidad= models.PositiveIntegerField()
    precioActual= models.FloatField(validators=[MinValueValidator(0.0)])
    subtotal = models.FloatField(validators=[MinValueValidator(0.0)])



class itemMayorista(models.Model):
    venta=models.ForeignKey(Venta, on_delete=models.CASCADE)
    mayorista_cuit=models.ForeignKey(Mayorista, on_delete=models.CASCADE)
  

class itemUsuario(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

apps/ventas/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Prefetch, F
from django.urls import reverse
from .forms import ventasForm, ItemProductoFormSet
from .models import itemMayorista, Venta, ItemProducto, Mayorista, itemUsuario
from apps.productos.models import Producto
from django.db import transaction
from django.contrib.auth.decorators import login_required,permission_required
# Create your views here.
from django.http import HttpResponse
from django.template.loader import render_to_string

@login_required
@permission_required('ventas.add_venta', raise_exception=True)
def registroVentas(request):
    if request.method == "POST":
        form = ventasForm(request.POST, request.FILES) 
        if form.is_valid():
            tipoVenta = form.cleaned_data.get('tipo_venta')
            try:
                with transaction.atomic():
                    ventaNueva = form.save()
                    if tipoVenta == 'MAYORISTA':
                        idMayorista = request.POST.get("cuitMayorista")
                        nuevaVentaMayorista = itemMayorista(
                            venta=ventaNueva,
                            mayorista_cuit_id=idMayorista
                        )
                        nuevaVentaMayorista.save()
                    idUsuario = request.POST.get("id_usuario")    
                    venta_usuario = itemUsuario(
                        venta = ventaNueva,
                        usuario_id = idUsuario
                    )
                    venta_usuario.save()
                    formset = ItemProductoFormSet(request.POST, instance=ventaNueva)
                    if formset.is_valid():
                        formset.save()
                        messages.success(request, "La venta se ha realizado exitosamente.")
                    else:
                        raise ValueError("Error en formset")
                    return redirect(f'http://{request.get_host()}/ventas/')
            except Exception as e:
                if "id_producto" in str(e):
                    mensaje_error = "CANTIDAD INVALIDA! LA VENTA NO SE PUDO REALIZAR"
                else:
                    mensaje_error = str(e)
                messages.error(request, mensaje_error)
                return redirect(reverse('ventas:registro_ventas'))
    form = ventasForm()
    formset = ItemProductoFormSet()
    return render(request, 'ventas/Registro_gestion_ventas.html', {'formVenta':form, 'formset':formset, 'id_usuario': request.user.id})    



@login_required
@permission_required('ventas.view_venta', raise_exception=True)
def informeVentas(request):
    ventas = Venta.objects.filter(itemusuario__isnull=False).select_related(
        'itemusuario__usuario'
    ).annotate(
        username=F('itemusuario__usuario__username')
    ).values(
        'id', 'numeroComprobante', 'FechaVenta', 'precioTotal',
        'observaciones', 'tipo_venta', 'tipo_comprobante', 'forma_pago', 'estado', 'username'
    ).order_by('-id') 
    return render (request, 'ventas/Lista_ventas.html',{
        'ventas': ventas
    })   

            # print(request.POST)  # Ver los datos que se están enviando
            # print(formset.errors) 
            # print(f'Número de formularios: {len(formset.save())}')  # Para ver cuántos formularios están en el formset


@login_required
@permission_required('ventas.view_venta', raise_exception=True)
def detalleVenta(request, id):
    venta_productos = (
        Venta.objects
        .filter(id=id)  # Filtra solo la venta específica
        .select_related("itemmayorista__mayorista_cuit")  # Para acceder a los datos del mayorista
        .prefetch_related(
            Prefetch("itemproducto_set", queryset=ItemProducto.objects.select_related("producto")),
            Prefetch("itemusuario_set", queryset=itemUsuario.objects.select_related("usuario"))
        )
        .values(
            "id", 
            "numeroComprobante", 
            "FechaVenta", 
            "precioTotal", 
            "observaciones", 
            "tipo_venta", 
            "tipo_comprobante", 
            "forma_pago", 
            "estado",
            # Campos de ItemProducto
            "itemproducto__producto_id", 
            "itemproducto__producto__descripcion", 
            "itemproducto__precioActual", 
            "itemproducto__cantidad", 
            "itemproducto__subtotal",
            "itemproducto__producto__categoria", 
            # Campos de Mayorista
            "itemmayorista__mayorista_cuit__cuit", 
            "itemmayorista__mayorista_cuit__razon_social",
            # Campos de Usuario asociado
            "itemusuario__usuario__cuit", 
            "itemusuario__usuario__username", 
            "itemusuario__usuario__email"
        )
    )
    return render(request, 'ventas/Detalles_venta.html', {'venta_productos':venta_productos})


def devolverCantidadStock(lst_venta_productos):
    for producto_venta in lst_venta_productos:
        idProducto = producto_venta['producto_id']
        cantidadVendida = producto_venta['cantidad']
        producto = get_object_or_404(Producto, id = idProducto)
        producto.cantidad += cantidadVendida
        producto.save()


@login_required
@permission_required('ventas.delete_venta', raise_exception=True)
def anularVenta(request, id):
    if request.method == 'POST':
        venta = get_object_or_404(Venta, id=id)
        productosAsociados = ItemProducto.objects.filter(venta_id=id).values('producto_id', 'cantidad')
        print(productosAsociados)
        devolverCantidadStock(productosAsociados)
        venta.estado = False
        venta.save()
        # messages.success(request, "La venta ha sido anulada exitosamente.")
        return redirect('ventas:informe_ventas')
    
    else:
        # messages.error(request, "La cancelación no se pudo completar.")
        return redirect('ventas:informe_ventas')


@login_required
@permission_required('ventas.add_mayorista', raise_exception=True)
def registroMayoristas(request):
    if request.method == 'POST':
        razonSocial = request.POST.get("razonSocial")
        cuit = request.POST.get("cuit")
        direccion = request.POST.get("direccion")
        telefono = request.POST.get("telefono")
        correo = request.POST.get("correo")
        condicionVenta = request.POST.get("condicionVenta")
        nuevoMayorista = Mayorista(
            cuit = cuit,
            razon_social = razonSocial,
            direccion = direccion,
            telefono = telefono,
            email = correo,
            condicion_venta = condicionVenta
        )
        nuevoMayorista.save()
    return render(request, 'ventas/Registro_mayoristas.html')


def informeMayoristas(request):
    mayoristas = Mayorista.objects.all()
    print(mayoristas)
    return render(request, "ventas/Lista_mayoristas.html", {'mayoristas':mayoristas})



def modificarMayorista(request, cuit):
    mayorista = get_object_or_404(Mayorista, cuit = cuit)
    if request.method == 'POST':
        mayorista.razon_social = request.POST.get("razonSocial")
        mayorista.cuit = request.POST.get("cuit")
        mayorista.direccion = request.POST.get("direccion")
        mayorista.telefono = request.POST.get("telefono")
        mayorista.email = request.POST.get("correo")
        mayorista.condicion_venta = request.POST.get("condicionVenta")
        mayorista.save()
        return redirect('ventas:informe_mayoristas')
    return render(request, "ventas/Modificar_mayorista.html", {'mayorista':mayorista})


def darDeBajaMayorista(request, cuit):
    if request.method == 'POST':
        mayorista = get_object_or_404(Mayorista, cuit = cuit)
        mayorista.estado = False
        mayorista.save()
        return redirect('ventas:informe_mayoristas')
    
def detallesMayorista(request, cuit):
    mayorista = get_object_or_404(Mayorista, cuit=cuit)
    return render(request, "ventas/Detalles_mayorista.html", {'mayorista':mayorista})


from django.http import HttpResponse
from fpdf import FPDF
from io import BytesIO
from .models import Venta  # Asegúrate de importar tu modelo Venta

class PDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.add_page('L')
    def header(self):
        self.set_font("Arial", "B", 12)
        self.cell(0, 10, "Informe de Ventas - Panadería El Maná", 0, 1, "C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, f"Página {self.page_no()}", 0, 0, "C")

@login_required
@permission_required('ventas.view_venta', raise_exception=True)
def generar_informe_pdf(request):
    # Filtra las ventas que tienen itemusuario asociado
    ventas = Venta.objects.filter(itemusuario__isnull=False).select_related(
        'itemusuario__usuario'
    ).annotate(
        username=F('itemusuario__usuario__first_name')
    ).values(
        'id', 'numeroComprobante', 'FechaVenta', 'precioTotal',
        'observaciones', 'tipo_venta', 'tipo_comprobante', 'forma_pago', 'estado', 'username'
    )

    # Crear instancia del PDF
    pdf = PDF()
    pdf.set_font("Arial", "B", 10)

    # Agregar encabezados de la tabla
    pdf.cell(20, 10, "ID", 1)
    pdf.cell(40, 10, "N° Comprobante", 1)
    pdf.cell(30, 10, "Fecha", 1)
    pdf.cell(50, 10, "Observaciones", 1)
    pdf.cell(30, 10, "Tipo de Venta", 1)
    pdf.cell(20, 10, "Estado", 1)
    pdf.cell(30, 10, "Vendedor", 1)  # Nueva columna para el nombre de usuario
    pdf.ln()

    # Agregar filas con datos de cada venta
    pdf.set_font("Arial", "", 10)
    for venta in ventas:
        pdf.cell(20, 10, str(venta['id']), 1)
        pdf.cell(40, 10, venta['numeroComprobante'], 1)
        pdf.cell(30, 10, venta['FechaVenta'].strftime("%Y-%m-%d"), 1)
        pdf.cell(50, 10, venta['observaciones'][:30], 1)  # Limita a 30 caracteres
        pdf.cell(30, 10, venta['tipo_venta'], 1)

apps/ventas/templates/ventas/Detalles_venta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Productos por Venta</title>
    {% extends 'base.html' %}
    {% load static %}
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/ventas/detallesVenta.css' %}">
    <link rel="stylesheet" href="{% static 'css/ventas/tabla2.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <style>
        .fondo-seccion {
            background-color: #0000005c;
            padding: 20px;
            border-radius: 5px;
            color: rgb(255, 255, 255);
        }
    </style>
    {% endblock css %}

</head>
<body>
    {% block content %}
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <p class="nav-link" style="color: white;"><b>ID Venta:</b> {{ venta_productos.0.id }}</p>
                  </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                      <p class="nav-link" style="color: white;"><b>Numero de comprobante:</b> {{ venta_productos.0.numeroComprobante }}</p>
                    </li>
                  </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item me-2">
                        <p class="nav-link " style="color: white;"><b>Fecha:</b> {{ venta_productos.0.FechaVenta }}</p>
                    </li>
                </ul>
              </div>
            </div>
          </nav>
          <br>
        <main class="p-4"> 
            <div class="fondo-seccion">
                <div class="container">
                    <div class="row d-flex justify-content-between">
                        <div class="col text-start"> 
                            <p><b>Tipo de venta:</b></p>
                            <p>{{ venta_productos.0.tipo_venta }}</p>
                        </div>
                        <div class="col text-center">
                            <p><b>Tipo de comprobante:</b></p>
                            <p>{{ venta_productos.0.tipo_comprobante }}</p>
                        </div>
                        <div class="col text-end"> 
                            <p><b>Forma de pago:</b></p> 
                            <p>{{ venta_productos.0.forma_pago }}</p>
                        </div>
                    </div>
                </div>
            </div>

           
           
            {% if venta_productos.0.tipo_venta == 'MAYORISTA' %}
                <hr><br><hr>
                
                <div class="fondo-seccion">
                    <p style="text-align: center;"><b>DATOS DEL MAYORISTA</b></p>
                    <div class="container">
                        <div class="row d-flex justify-content-between">
                            <div class="col text-start"> 
                                <p><b>CUIT:</b></p>
                                <p>{{ venta_productos.0.itemmayorista__mayorista_cuit__cuit }}</p>
                            </div>
                            <div class="col text-center"> 
                                <a href="#" class="btn-mayorista" id="btnMay" data-cuit="{{ venta_productos.0.itemmayorista__mayorista_cuit__cuit }}">Ver más detalles</a>
                            </div>
                            <div class="col text-end"> 
                                <p><b>RAZON SOCIAL:</b></p>
                                <p>{{ venta_productos.0.itemmayorista__mayorista_cuit__razon_social }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
            {% endif %}
            <br>
            <hr>

            <div class="fondo-seccion">
                <div class="tituloTabla">
                    <b>Productos:</b>
                </div>
            
                <div class="tablaProductos">
                    <table border="1">
                        <thead>
                            <tr>
                                <th>ID Producto</th>
                                <th>Producto</th>
                                <th>Categoria</th>
                                <th>Precio</th>
                                <th>Cantidad</th>
                                <th>Subtotal</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ventap in venta_productos %}
                                <tr>
                                    <td>{{ ventap.itemproducto__producto_id }}</td>
                                    <td>{{ ventap.itemproducto__producto__descripcion }}</td>
                                    <td>{{ ventap.itemproducto__producto__categoria }}</td>
                                    <td>{{ ventap.itemproducto__precioActual }}</td>
                                    <td>{{ ventap.itemproducto__cantidad }}</td>
                                    <td>{{ ventap.itemproducto__subtotal }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot class="total-row" id="foot-tr">
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><b>TOTAL: </b></td>
                            <td><b>{{ venta_productos.0.precioTotal }}</b></td>
                        </tfoot>
                    </table>
                </div>
            </div>
            <hr>
            <br>
            <hr>
            <div class="fondo-seccion">
                <div class="observaciones">
                    <p><b>Observaciones:</b></p>
                    <textarea readonly>{{ venta_productos.0.observaciones }}</textarea>
                </div>
            </div>
            <hr>
            <br>
            <hr>
            <div class="fondo-seccion">
            <div class="container">
            <div class="row d-flex justify-content-between">
                <p style="text-align: center;"><b>Datos del vendedor</b></p>
                <div class="col text-start">
                    <p><b>Username:</b></p>
                    <p>{{venta_productos.0.itemusuario__usuario__username}}</p>
                </div>
                <div class="col text-center"> 
                    <p><b>Cuit:</b></p>
                    <p>{{venta_productos.0.itemusuario__usuario__cuit}}</p>
                </div>
                <div class="col text-end"> 
                    <p><b>Email: </b></p>
                    <p>{{venta_productos.0.itemusuario__usuario__email}}</p>
                </div>
            </div>
            </div>
            </div>
            <hr><br>          
            <div class="row d-flex justify-content-between">
                {% if not venta_productos.0.estado %}
                <div class="col text-start"> 
                    <p><b>Estado de venta: </b><span style="color: rgb(255, 0, 0);" id="estadoVenta"><b>ANULADA</b></span></p>
                </div>
                {% else %}
                <div class="col text-start">
                    <p><b>Estado de venta: </b><span style="color: green;" id="estadoVenta"><b>EXITOSA</b></span></p>
                </div>
                <div class="col text-end"> 
                    <div class="div_anular_venta">
                    {% if perms.ventas.delete_venta %}
                    <form action="" id="formulario_anular" class="needs-validation formulario" method="post">
                        {% csrf_token %}
                        <button id="btn_anularVenta" type="button" onclick="confirmCancel(`{% url 'ventas:anular_venta' venta_productos.0.id %}`)"><i class="fa-solid fa-trash fa-sm" style="color: #ffffff;" id="iconoBasura"></i>Anular venta</button>
                    </form>
                    {% endif %}
                    </div>
                </div>
                {% endif %}
            </div>            
        </main>
    </div>
    {% endblock %}
    {% block js %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="/static/scripts/gestion_ventas/script_detalles.js"></script>
    <script>
        const $btnMayorista = document.getElementById("btnMay");
        $btnMayorista.addEventListener("click", function(e){
            window.location.href = `mayoristas/detalles/${$btnMayorista.dataset.cuit}`;
        })
    </script>
    {% endblock %}
</body>
</html>

apps/ventas/templates/ventas/Lista_mayoristas.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión de Ventas - Panadería El Maná</title>
    {% extends 'base.html' %}
    {% load static %}
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/ventas/style_gestion_venta.css' %}">
    <link rel="stylesheet" href="{% static 'css/ventas/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/ventas/tabla2.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">

    <style>
        .table-input-container-list{
            display: grid;
            grid-template-columns: 0.4fr 0.4fr 0.4fr 0.3fr;
        }
        .formulario__input_list{
            max-width: 250px;
            width: 100%;
            background: #fff;
            border: 3px solid transparent;
            border-radius: 3px;
            height: 45px;
            line-height: 45px;
            padding: 0 40px 0 10px;
            transition: .3s ease all;
        }
        
        .table-buttons-list{
            cursor: pointer;
            height: 50px;
            line-height: 20px;
            max-width: 200px;
            width: 100%;
            color: black;
            border: none;
            border-radius: 8px;
            transition: .1s ease all;
            margin-top: 20px;
           
            margin-bottom: 10px;
        }
        .action-item-list{
            display: flex;
            justify-content: center;
            gap: 5px;

        }

    </style>
    {% endblock %}
</head>

<body>
    {% block content %}
    <main id="main">
        <!-- <div class="card-header navbar-dark" style="display: flex">
            <h1 class="h3 mb-0 formulario__label"style="color: #ffffff"></h1>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li class="{{ message.tags }} mensajes">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="table-container" id="tabla" style="text-align: center;">
            <div class="table-title">Lista de Ventas</div>
            <div class="table-input-container-list">
                <div class="formulario__grupo" id="grupo__searchInputID">
                    <label for="searchInputID" class="formulario__label">Comprobante</label>
                    <div class="formulario__grupo-input">
                        <input type="text" class="formulario__input_list" id="searchInputID" placeholder="Buscar por Comprobante" onkeyup="buscarVenta()">   
                    </div>
                </div>
                <div class="formulario__grupo" id="grupo__fechaTablaMin">
                    <label for="searchInputDateMin" class="formulario__label">Fecha Mínima</label>
                    <div class="formulario__grupo-input">
                        <input type="date" class="formulario__input_list" id="searchInputDateMin" placeholder="Fecha mínima">
                    </div>
                </div>
                <div class="formulario__grupo" id="grupo__fechaTablaMax">
                    <label for="searchInputDateMax" class="formulario__label">Fecha Máxima</label>
                    <div class="formulario__grupo-input">
                        <input type="date" class="formulario__input_list" id="searchInputDateMax" placeholder="Fecha máxima">                 
                    </div>             
                </div>
                <div class="formulario__grupo" id="grupo__fechaTablaMax">
                    <label for="tipoVenta_b" class="formulario__label">Tipo de venta</label>
                    <div class="formulario__grupo-input">
                        <select name="tipoVenta_b" id="tipoVenta_b" class="formulario__input_list">
                            <option value="todas">Todas</option>
                            <option value="minorista">Minorita</option>
                            <option value="mayorista">Mayorista</option>
                        </select>
                    </div>             
                </div>
                <div class="formulario__grupo" id="grupo__fechaTablaMax">
                    <label for="estadoVenta_b" class="formulario__label">Estado</label>
                    <div class="formulario__grupo-input">
                        <select name="estadoVenta_b" id="estadoVenta_b" class="formulario__input_list">
                            <option value="todas">Todas</option>
                            <option value="exitosa" style="color: green; font-weight: bold;">Exitosa</option>
                            <option value="anulada" style="color: red; font-weight: bold;">Anulada</option>
                        </select>            
                    </div>             
                </div>
                <div class="formulario__grupo" id="grupo__buscarTabla">
                    <label for="buscarTabla" class="formulario__label"></label>
                  
                        <button type="button" class="table-buttons-list" id="buscarTabla" onclick="buscarVenta()">Buscar</button>
                </div>
            </div> -->
            <table style="width: max-content;">
                
                <thead>
                    <tr>
                        <th>Cuit</th>
                        <th>Razon Social</th>
                        <th>Direccion</th>
                        <th>Telefono</th>
                        <th>Email</th>
                        <th>Condicion de venta</th>
                        <th>Estado</th>
                        {% if perms.ventas.change_mayorista %}
                        <th>Acción</th>
                        {%endif%}
                    </tr>
                </thead>
                <tbody class="tbody">
                    {% for mayorista in mayoristas %}
                    <tr>
                        <td>{{ mayorista.cuit }}</td>
                        <td>{{ mayorista.razon_social }}</td>
                        <td>{{ mayorista.direccion }}</td>
                        <td>{{ mayorista.telefono }}</td>
                        <td>{{ mayorista.email }}</td>
                        <td>{{ mayorista.condicion_venta }}</td>
                        {% if mayorista.estado %}
                        <td style="color: green;"><b>ACTIVO</b></td>
                        {% else %}
                        <td style="color: red;"><b>INACTIVO</b></td>
                        {% endif %}
                        {% if perms.ventas.change_mayorista %}
                        <td class="action-item-list">
                            <button type="button" class="action-button edit-button" data-cuit="{{ mayorista.cuit }}">
                                <i class="fa-regular fa-file-lines" style="color: #ffffff;" data-cuit="{{ mayorista.cuit }}"></i>
                            </button>
                            {% if mayorista.estado %}
                            {% if perms.ventas.delete_mayorista %}
                            <form action="" id="formulario_anular" class="needs-validation formulario" method="post">
                                {% csrf_token %}
                                <button type="button" class="action-button delete-button" onclick="confirmCancel(`{% url 'ventas:baja_mayorista' mayorista.cuit %}`)">
                                    <i class="fa-solid fa-trash fa-sm" style="color: #ffffff;"></i>
                                </button>
                            </form>
                            {% endif %}
                            {% endif %}
                        </td>
                        {% endif %}
                    </tr>
                    
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr class="total-row" id="foot-tr">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        {% if perms.ventas.change_mayorista %}
                        <td></td>
                        {% endif %}
                    </tr>
                </tfoot>
            </table>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{% static 'scripts/script_tabla.js' %}"></script>
    <script src="{% static 'scripts/gestion_ventas/script_tabla_mayoristas.js' %}"></script>
    {% endblock %}
</body>

</html>