PanaderiaElMana/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('apps.usuarios.urls', namespace='usuarios')),
    path('pedidos/', include('apps.pedidos.urls', namespace='pedidos')),
    path('ventas/', include('apps.ventas.urls', namespace='ventas')),
    path('productos/', include('apps.productos.urls', namespace='productos')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/productos/urls.py
from django.urls import path
from apps.productos import views 

app_name = 'productos'
urlpatterns = [
    path('', views.gestionarProductos, name='gestionarProductos'),
    path('baja_cantidad', views.productosCantidadBaja, name='baja_cantidad'),
    path('editar/<int:pk>', views.editarProductos, name='editar_productos'),
    path('eliminar/<int:pk>', views.eliminarProductos, name='eliminar_productos'),
    path('informe', views.informeProductos, name='informe_productos'),
]

apps/productos/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.


class Producto(models.Model):

    descripcion= models.TextField(max_length=100,null=True)
    precio= models.FloatField(validators=[MinValueValidator(0)])
    cantidad= models.FloatField(validators=[MinValueValidator(0)])
    cantidad_minima= models.FloatField(validators=[MinValueValidator(0)])
    unidad_medida= models.CharField(max_length=10)
    estado=models.BooleanField(default=True)
    categoria = models.CharField(max_length=15)

    def __str__(self):
        return f"{self. descripcion} (precio:{self.precio}) (cant:{self.cantidad})"

#opcion: mandar esos 2 y con las expReg en js capturar el precio del option seleccionado

apps/productos/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    
    categorias = [("", "Seleccione"), ("PAN", "Panificación"), ("PAS", "Pastelería")]
    categoria = forms.ChoiceField(choices=categorias,
                widget=forms.Select(attrs={'class': 'formulario__input','id':'categoria_producto',}))
    
    unidades_de_medida = [("", "Seleccione"), ("kg", "Kilogramos"), ("unidades", "Unidades")]
    unidad_medida = forms.ChoiceField(choices=unidades_de_medida,
                widget=forms.Select(attrs={'class': 'formulario__input','id':'unidad_medida',}))

    class Meta:

        model = Producto
        fields = ['descripcion', 'precio', 'cantidad', 'cantidad_minima', 'unidad_medida', 'categoria']

        widgets = {

            'descripcion': forms.TextInput(attrs={
                'class': 'formulario__input', 
                'id': 'descripcion_producto',
               
            }),
            'precio': forms.NumberInput(attrs={
                'class': 'formulario__input', 
                'id': 'precio_producto',
            }),
            'cantidad': forms.NumberInput(attrs={
                'class': 'formulario__input', 
                'id': 'cantidad_producto',
            }),
            'cantidad_minima': forms.NumberInput(attrs={
                'class': 'formulario__input', 
                'id': 'cantidad_minima_producto',
            })
        }

 

apps/productos/views.py
from django.http import JsonResponse
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .forms import ProductoForm
from .models import Producto
from django.db.models import Q
from django.contrib.auth.decorators import login_required,permission_required
from django.db.models import F
from django.db.models.functions import Abs


@login_required
def productosCantidadBaja(request):
    productos = Producto.objects.filter(cantidad__lte=F('cantidad_minima'), estado=True).values('id', 'cantidad_minima','descripcion', 'cantidad')
    return JsonResponse(list(productos), safe=False)



@login_required
@permission_required('productos.view_producto', raise_exception=True)
def gestionarProductos(request):
    nuevo_producto = None
    productos = Producto.objects.filter(estado=True)

    if request.method == 'POST':
        producto_form = ProductoForm(request.POST, request.FILES)
        if producto_form.is_valid():

            descripcion = producto_form.cleaned_data['descripcion'].lower()

            if Producto.objects.filter(Q(descripcion__iexact=descripcion), estado=True).exists():
                messages.error(request, 'El producto ya existe')
                return render(request, 'productos/Gestion-productos.html', {'producto_form': producto_form,'productos':productos})
            else:
                nuevo_producto = producto_form.save(commit=False)
                nuevo_producto.save()
                messages.success(
                request,
                "Producto agregado exitosamente")
                return redirect(reverse('productos:gestionarProductos'))
                
    else:
        producto_form = ProductoForm()
    return render(request, 'productos/Gestion-productos.html', {'producto_form': producto_form,'productos':productos})


@login_required
@permission_required('productos.change_producto', raise_exception=True)
def editarProductos(request, pk):
    productos= Producto.objects.filter(estado=True)
    producto = get_object_or_404(Producto, pk=pk)
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES, instance=producto)
        if form.is_valid():

            descripcion = form.cleaned_data['descripcion'].lower()

            existe_producto = Producto.objects.filter(
                Q(descripcion__iexact=descripcion)
            , estado=True).exclude(id=producto.id).exists()

            if existe_producto:
                messages.error(request, 'El producto ya existe')
                return render(request, 'productos/editar-productos.html', {'form': form, 'producto': producto, 'productos':productos})
            producto = form.save()
            messages.success(request, "El producto ha sido modificado exitosamente.")
            print('Datos recibidos:', request.POST)
            return redirect('productos:gestionarProductos')
        
        return render(request, 'productos/editar-productos.html', {
                'form': form,
                'producto': producto,
                'productos': productos,
            })
    else:
        form = ProductoForm(instance=producto)

    return render(request, 'productos/editar-productos.html', {
        'form': form,
        'producto': producto,
        'productos': productos
    })


@login_required
@permission_required('productos.delete_producto', raise_exception=True)
def eliminarProductos(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    
    if request.method == 'POST':
        print("Estado anterior:", producto.estado)
        producto.estado = False
        producto.save()
        messages.success(request, "El producto ha sido eliminado exitosamente.")
        return redirect('productos:gestionarProductos')
    
    else:
        messages.error(request, "La cancelación no se pudo completar.")
        return redirect('productos:gestionarProductos')

@login_required
@permission_required('productos.view_producto', raise_exception=True)
def informeProductos(request):
    productos = Producto.objects.filter(estado=True)

    # Filtrar por categoría (si se proporciona)
    categoria = request.GET.get('categoria')
    if categoria:
        productos = productos.filter(categoria=categoria)

    # Ordenar por cantidad disponible (cantidad - cantidad_minima)
    orden = request.GET.get('orden')
    if orden == 'asc':
        productos = productos.order_by(Abs(F('cantidad') - F('cantidad_minima')))
    elif orden == 'desc':
        productos = productos.order_by(Abs(F('cantidad') - F('cantidad_minima'))).reverse()

    return render(request, 'productos/Informe-productos.html', {
        'productos': productos,
        'categoria_seleccionada': categoria,
        'orden': orden
    })

apps/productos/templates/productos/Editar-productos.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Gestión de Productos</title>
        {% extends 'base.html' %}
        {% load static %}
        {% block css %}
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'css/productos/tabla.css' %}">
        <link rel="stylesheet" href="{% static 'css/productos/style_gestion_productos.css' %}">
        <link rel="stylesheet" href="{% static 'css/productos/form.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </head>
    {% block content %}
    <body>

        <main id="main">
            {% if perms.productos.add_producto and perms.productos.change_producto and perms.productos.delete_producto %}
            <form id="formulario" class="needs-validation formulario" method="post">
            {% csrf_token %}
                <div class="card-header navbar-dark" style="display: flex">
                    <h1 class="h3 mb-0 formulario__label"style="color: #ffffff">Producto</h1>
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li class="{{ message.tags }} mensajes">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="form-container">
                    <div class="form-background">

                        <div class="formulario__grupo" id="grupo__descripcion">
                            <label for="desc_producto" class="formulario__label">Descripción del producto</label>
                            <div class="formulario__grupo-input">
                                {{ form.descripcion}}
                                {% for error in form.descripcion.errors %}
                                    <div class="error"><p>Ingresa una descripcion válida</p></div>
                                {% endfor %}
                            </div>
                        </div>
                        
                        <div class="formulario__grupo" id="grupo__categoria">
                            <label for="categoria_panificacion" class="formulario__label">Categoria de producto</label>
                            <div class="formulario__grupo-input">
                                {{form.categoria}}
                                {% for error in form.categoria.errors %}
                                    <div class="error"><p>Ingresa una categoria</p></div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="formulario__grupo" id="grupo__precioProducto">
                            <label for="costo_producto" class="formulario__label">Precio del producto</label>
                            <div class="formulario__grupo-input">
                                {{ form.precio}}
                                {% for error in form.precio.errors %}
                                    <div class="error"><p>Ingresa un precio válido</p></div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="formulario__grupo" id="grupo__precioProducto">
                            <label for="cant_producto" class="formulario__label">Cantidad disponible</label>
                            <div class="formulario__grupo-input">
                                {{ form.cantidad}}
                                {% for error in form.cantidad.errors %}
                                    <div class="error"><p>Ingresa una cantidad válida</p></div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="formulario__grupo" id="grupo__precioProducto">
                            <label for="cantidad_minima_producto" class="formulario__label">Cantidad minima</label>
                            <div class="formulario__grupo-input">
                                {{ form.cantidad_minima}}
                                {% for error in form.cantidad_minima.errors %}
                                    <div class="error"><p>Ingresa una cantidad válida</p></div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="formulario__grupo" id="grupo__precioProducto">
                            <label for="unidad_medida" class="formulario__label">Unidad de medida</label>
                            <div class="formulario__grupo-input">
                                {{ form.unidad_medida}}
                                {% for error in form.unidad_medida.errors %}
                                    <div class="error" style="color: red;"><p>Ingresa una unidad válida</p></div>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                </div>

                <div class="formulario__grupo formulario__grupo-btn-enviar">
                    <button type="submit" name="Editar" id="boton_editar" class="formulario__btn">
                    <i class="fa-solid fa-pen-to-square fa-sm me-2"></i>Editar
                    </button>
                </div>
            </form>

            <div class="table-container" id="tableContainer">
                <div class="table-title">Lista de Productos</div>
                <table>
                    <thead>
                        <tr>
                            <th>Descripción</th>
                            <th>Precio</th>
                            <th>Cantidad</th>
                            <th>U. Medida</th>
                            <th>Categoria</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody class="tbody">
                        {% for producto in productos %}
                        <tr>
                            <td>{{ producto.descripcion }}</td>
                            <td>{{ producto.precio }}</td>
                            <td>{{ producto.cantidad }}</td>
                            <td>{{ producto.unidad_medida }}</td>
                            <td>{{ producto.categoria }}</td>
                            <td class="action-item-list">
                                <button class="action-button edit-button"><a href="{% url 'productos:editar_productos' producto.id %}" style="color: white;">
                                    <i class="fas fa-edit" style="color: white;"></i></button>
                                    </a>
                                <form action="" id="formulario_eliminar" class="needs-validation formulario" method="post">
                                    {% csrf_token %}
                                    <button type="button" class="action-button delete-button"  onclick="confirmCancel(`{% url 'productos:eliminar_productos' producto.id %}`)"><i class="fas fa-trash-alt" style="color: #ffffff;"></i></button>
                                </form>
                            </td>       
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                    <tfoot>          
                        <tr class="total-row" id="foot-tr">
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tfoot> 
                </table>
            </div>
            {% endif %}

        </main>

        {% endblock %}

        {% block js %}
        <script src="{% static 'scripts/Validacion-ModificacionProductos.js'%}"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        {% endblock %}
    </body>
</html>

apps/productos/templates/productos/Gestion-productos.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Gestión de Productos</title>
        {% extends 'base.html' %}
        {% load static %}
        {% block css %}
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'css/productos/tabla.css' %}">
        <link rel="stylesheet" href="{% static 'css/productos/style_gestion_productos.css' %}">
        <link rel="stylesheet" href="{% static 'css/productos/form.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </head>
    {% block content %}
    <body>
        
        <main id="main">
            {% if perms.productos.add_producto %}
            <form id="formulario" class="needs-validation formulario" method="post">
            {% csrf_token %}
                <div class="card-header navbar-dark" style="display: flex">
                    <h1 class="h3 mb-0 formulario__label"style="color: #ffffff">Producto</h1>
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li class="{{ message.tags }} mensajes">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="form-container">
                    <div class="form-background">

                        <div class="formulario__grupo" id="grupo__descripcion">
                            <label for="desc_producto" class="formulario__label">Descripción del producto</label>
                            <div class="formulario__grupo-input">
                                {{ producto_form.descripcion}}
                            </div>
                        </div>
                        
                        <div class="formulario__grupo" id="grupo__categoria">
                            <label for="categoria_panificacion" class="formulario__label">Categoria de producto</label>
                            <div class="formulario__grupo-input">
                                {{producto_form.categoria}}
                                {% for error in producto_form.categoria.errors %}
                                    <div class="error"><p>Ingresa una categoría válida</p></div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="formulario__grupo" id="grupo__precioProducto">
                            <label for="costo_producto" class="formulario__label">Precio del producto</label>
                            <div class="formulario__grupo-input">
                                {{ producto_form.precio}}
                                {% for error in producto_form.precio.errors %}
                                    <div class="error"><p>Ingresa un precio válido</p></div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="formulario__grupo" id="grupo__precioProducto">
                            <label for="cant_producto" class="formulario__label">Cantidad disponible</label>
                            <div class="formulario__grupo-input">
                                {{ producto_form.cantidad}}
                                {% for error in producto_form.cantidad.errors %}
                                    <div class="error"><p>Ingresa una cantidad válida</p></div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="formulario__grupo" id="grupo__precioProducto">
                            <label for="cantidad_minima_producto" class="formulario__label">Cantidad minima</label>
                            <div class="formulario__grupo-input">
                                {{ producto_form.cantidad_minima}}
                                {% for error in producto_form.cantidad_minima.errors %}
                                    <div class="error"><p>Ingresa una cantidad válida</p></div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="formulario__grupo" id="grupo__precioProducto">
                            <label for="unidad_medida" class="formulario__label">Unidad de medida</label>
                            <div class="formulario__grupo-input">
                                {{ producto_form.unidad_medida}}
                                {% for error in producto_form.unidad_medida.errors %}
                                    <div class="error"><p>Ingresa una unidad válida</p></div>
                                {% endfor %}
                            </div>
                        </div>
                        
                    </div>
                    {% if messages %}
                    {% for message in messages %}
                            {% if "error" in message.tags %}
                                <div class="formulario__mensaje formulario__mensaje-activo" id="formulario__mensaje">
                                    <p class="{{ message.tags }}"><i class="fas fa-exclamation-triangle"></i> <b>Error:</b> {{ message }}</p>
                                </div>
                            {% elif "success" in message.tags %}
                                <div class="formulario__mensaje-exito formulario__mensaje-exito-activo" id="formulario__mensaje-exito">
                                    <p class="{{ message.tags }}"><i class="fas fa-exclamation-triangle"></i> <b>Éxito:</b> {{ message }}</p>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>

                
                <div class="formulario__grupo formulario__grupo-btn-enviar">
                    <button type="submit" name="Agregar" id="boton_agregar" class="formulario__btn"><i class="bi bi-send me-2"></i>Agregar</button>
                    </button>
                </div>
            </form>
            {% endif %} 

            <div class="table-container" id="tableContainer" >
                <div class="table-title">Lista de Productos</div>
                <table>
                    <thead>
                        <tr>
                            <th>Descripción</th>
                            <th>Precio</th>
                            <th>Cantidad</th>
                            <th>U. Medida</th>
                            <th>Categoria</th>
                            {% if perms.productos.add_producto %}
                            <th>Acciones</th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody class="tbody">
                        {% for producto in productos %}
                        <tr>
                            <td>{{ producto.descripcion }}</td>
                            <td>{{ producto.precio }}</td>
                            <td>{{ producto.cantidad }}</td>
                            <td>{{ producto.unidad_medida }}</td>
                            <td>{{ producto.categoria }}</td>
                            {% if perms.productos.add_producto %}
                            <td class="action-item-list">
                                <button type="button" class="action-button edit-button"><a href="{% url 'productos:editar_productos' producto.id %}" style="color: white;">
                                <i class="fas fa-edit" style="color: white;"></i></button>
                                </a>
                                <form action="" id="formulario_eliminar" method="post">
                                    {% csrf_token %}
                                    <button type="button" class="action-button delete-button" onclick="confirmCancel(`{% url 'productos:eliminar_productos' producto.id %}`)"><i class="fas fa-trash-alt" style="color: #ffffff;"></i></button>
                                </form>
                            </td>   
                            {% endif %}    
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                    <tfoot>          
                        <tr class="total-row" id="foot-tr">
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            {% if perms.productos.add_producto %}
                            <td></td>
                            {% endif %}    

                        </tr>
                    </tfoot> 
                </table>
            </div>
            

        </main>


       
        {% endblock %}

        {% block js %}
        <script src="{% static 'scripts/Validacion-GestionProductos.js'%}"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        {% endblock %}
    </body>
</html>

apps/productos/templates/productos/Informe-productos.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Informe de Productos</title>
        {% extends 'base.html' %}
        {% load static %}
        {% block css %}
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/productos/tabla.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" href="{% static 'css/productos/informe.css' %}">
        <link rel="stylesheet" href="{% static 'css/productos/form.css' %}">

        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </head>
    {% block content %}
    <body>
        <main id="main">

            <!-- Filtros por categoría -->
            <form id="formulario" class="needs-validation formulario" method="GET">
                <label for="categoria" class="formulario__label">Filtrar por Categoría:</label>
                <select name="categoria" id="categoria" class="formulario__input">
                    <option value="">Todas</option>
                    <option value="PAN" {% if categoria_seleccionada == "PAN" %}selected{% endif %}>Panificación</option>
                    <option value="PAS" {% if categoria_seleccionada == "PAS" %}selected{% endif %}>Pastelería</option>
                    <!-- Agrega más categorías según tu necesidad -->
                </select>

                <!-- Botones para ordenar por cantidad -->
                <button type="submit" name="orden" value="asc" class="formulario__btn">Ordenar por menor cantidad restante</button>
                <button type="submit" name="orden" value="desc" class="formulario__btn">Ordenar por mayor cantidad restante</button>
            </form>

            <div class="table-container" id="tableContainer" >
                <div class="table-title">Lista de productos</div>
                <table id="tabla-productos">
                    <thead>
                        <tr>
                            <th>Descripción</th>
                            <th>Precio</th>
                            <th>Cantidad disponible</th>
                            <th>Cantidad minima</th>
                            <th>Unidad de Medida</th>
                            <th>Categoría</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for producto in productos %}
                        <tr>
                            <td>{{ producto.descripcion }}</td>
                            <td>{{ producto.precio }}</td>
                            <td>{{ producto.cantidad }}</td>
                            <td>{{ producto.cantidad_minima }}</td>
                            <td>{{ producto.unidad_medida }}</td>
                            <td>{{ producto.categoria }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>          
                        <tr class="total-row" id="foot-tr">
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td> 

                        </tr>
                    </tfoot> 
                </table>
                <button class="formulario__btn" onclick="window.print()">Imprimir informe</button>
            </div>
        </main>
        {% endblock %}

        {% block js %}
        <script>document.addEventListener('click',function(e){
                console.log(e.target)
            })
            const selectElement = document.getElementById('categoria');

            selectElement.addEventListener('change', () => {
                document.getElementById('formulario').submit()
        
            });
        </script>
        {% endblock %}
    </body>
</html>