PanaderiaElMana/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('apps.usuarios.urls', namespace='usuarios')),
    path('pedidos/', include('apps.pedidos.urls', namespace='pedidos')),
    path('ventas/', include('apps.ventas.urls', namespace='ventas')),
    path('productos/', include('apps.productos.urls', namespace='productos')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pedidos/urls.py
from django.urls import path
from apps.pedidos import views 

app_name = 'pedidos'
urlpatterns = [
    path('', views.registroPedidos, name='registro_pedidos'),
    path('lista/',views.pedidos,name='lista_pedidos'),
    path('detalle/<int:pk>', views.editarPedidos, name='editarPedidos'),
    path('cancelar/<int:pk>', views.cancelarPedido, name='cancelarPedido'),
    path('lista_recepcion/',views.listaRecepcion,name='listaRecepcion'),
    path('recepcionar/<int:pk>', views.recepcionarPedidos, name='recepcionarPedidos'),
    path('insumos', views.gestionarInsumos, name='gestionarInsumos'),
    path('insumos/editar/<int:pk>', views.editarInsumos, name='editar_insumos'),
    path('insumos/eliminar/<int:pk>', views.eliminarInsumos, name='eliminar_insumos'),
    path('insumos/restar/', views.restarInsumos, name='restar_insumos'),
    path('informe', views.informeInsumos, name='informe_insumos'),
]

apps/pedidos/models.py
from django.db import models

# Create your models here.

class Proveedor(models.Model):
    cuit= models.CharField(max_length=11,primary_key=True)
    nombre= models.TextField(max_length=50)
    email= models.CharField(max_length=50)
    direccion= models.TextField(max_length=50)
    telefono= models.CharField(max_length=20)
    estado=models.BooleanField(default=True)

    def __str__(self):
        return f"{self. nombre}"





class Insumo(models.Model):

    descripcion= models.TextField(max_length=100,null=True)
    cantidad= models.FloatField()
    cantidad_minima= models.FloatField()
    unidad_medida= models.CharField(max_length=10,blank=True)
    estado=models.BooleanField(default=True)

    def __str__(self):
        return f"{self.descripcion}"





class Pedido(models.Model):

    fecha_pedido= models.DateField()
    observaciones= models.TextField(max_length=100 ,blank=True, null=True)
    proveedor= models.ForeignKey(Proveedor,on_delete=models.CASCADE)
    estado=models.BooleanField(default=True)

    def __str__(self):
        return f"Fecha de pedido: {self.fecha_pedido} Observaciones: {self.observaciones} proveedor: {self.proveedor.nombre}"



class ItemInsumo(models.Model):
    pedido= models.ForeignKey(Pedido, on_delete=models.CASCADE,related_name="insumos")
    insumo= models.ForeignKey(Insumo, on_delete=models.CASCADE)
    cantidad= models.FloatField()
    unidad_medida= models.CharField(max_length=10,blank=True)




class RecepcionPedidos(models.Model):
    
    fecha_llegada=models.DateField(auto_now=True)
    observacion= models.TextField(max_length=100 ,blank=True, null=True)
    conformidad= models.BooleanField()
    precio_total= models.FloatField(default=0)   
    pedido= models.ForeignKey(Pedido,on_delete=models.CASCADE)
    

class RestarInsumos(models.Model):
    insumo= models.ForeignKey(Insumo, on_delete=models.CASCADE)
    unidad_medida= models.CharField(max_length=10,blank=True)
    cantidad_restar= models.FloatField()

apps/pedidos/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from .models import Insumo,Pedido,ItemInsumo,RecepcionPedidos
from .forms import PedidoForm, ItemInsumoFormSet,RecepcionForm, InsumoForm,RestarInsumoFormSet
from django.urls import reverse
from django.db.models import Q,F
from django.contrib.auth.decorators import login_required,permission_required
from django.db.models.functions import Abs



# Create your views here.

@login_required
@permission_required('pedidos.view_pedido', raise_exception=True)
def pedidos(request):
    pedidos=Pedido.objects.all().order_by('-id')
    return render (request, 'pedidos/Lista-pedidos.html',{
        'pedidos':pedidos
    })

@login_required
@permission_required('pedidos.add_pedido', raise_exception=True)
def registroPedidos(request):

    insumos= Insumo.objects.filter(estado=True)
    
    if request.method == 'POST':
        print('entro a pos')
        form = PedidoForm(request.POST,request.FILES)      
        print(form)
        if form.is_valid():
            print(' es valido')
            pedido = form.save()
            formset = ItemInsumoFormSet(request.POST, instance=pedido)
            print('formset',formset)
            
            if formset.is_valid():
                print('valido formest')
                formset.save()
                messages.success(request, 'pedido creado exitosamente.')
                return redirect('pedidos:lista_pedidos')
                
    else:
        form = PedidoForm()
        formset = ItemInsumoFormSet()

    return render(request, 'pedidos/Registro-gestion-pedidos.html', {
        'formPedido': form,
        'formset': formset,
        'insumos':insumos
    })



@login_required
@permission_required('pedidos.view_pedido', raise_exception=True)
def editarPedidos(request, pk):
    insumos= Insumo.objects.filter(estado=True)
    pedido = get_object_or_404(Pedido, pk=pk)
    if request.method == 'POST':
        form = PedidoForm(request.POST, request.FILES, instance=pedido)
        if form.is_valid():
            pedido = form.save()
            formset = ItemInsumoFormSet(request.POST, instance=pedido)
            if formset.is_valid():
                formset.save()
                messages.success(request, 'Pedido actualizado exitosamente.')
                return redirect('pedidos:lista_pedidos')
    else:
        form = PedidoForm(instance=pedido)
        formset = ItemInsumoFormSet(instance=pedido)

    return render(request, 'pedidos/Detalle-pedido.html', {
        'form': form,
        'formset': formset,
        'pedido': pedido,
        'insumos':insumos
    })


@login_required
@permission_required('pedidos.delete_pedido', raise_exception=True)
def cancelarPedido(request, pk):
    print("Cancelando pedido con ID:", pk)  # Agrega esta línea
    pedido = get_object_or_404(Pedido, pk=pk)
    
    if request.method == 'POST':
        pedido.estado = False
        pedido.save()
        messages.success(request, "El pedido ha sido cancelado exitosamente.")
        return redirect('pedidos:lista_pedidos')
    
    else:
        messages.error(request, "La cancelación no se pudo completar.")
        return redirect('pedidos:lista_pedidos')
    

@login_required
@permission_required('pedidos.view_recepcionpedidos', raise_exception=True)
def listaRecepcion(request):
    pedidos=Pedido.objects.all().order_by('-id')
    return render (request, 'pedidos/Lista-recepcion.html',{
        'pedidos':pedidos
    })


@login_required
@permission_required('pedidos.view_recepcionpedidos', raise_exception=True)
def recepcionarPedidos(request, pk):
    pedido = get_object_or_404(Pedido, pk=pk)
    formpedido = PedidoForm(request.POST, request.FILES, instance=pedido)
   

    if request.method == 'POST':
        form = RecepcionForm(request.POST,request.FILES)
        formset = ItemInsumoFormSet(request.POST,instance=pedido)
        print(form)
        if form.is_valid():
            recepcion = form.save(commit=False)  
            recepcion.pedido = pedido  
            recepcion.save()  

            for form in formset[:-1]:
                item_insumo = form.save(commit=False)
                insumo = item_insumo.insumo
                insumo.cantidad += item_insumo.cantidad
                insumo.save()      

            pedido.estado = False
            pedido.save()
            messages.success(request, 'Pedido reservado exitosamente.')
            return redirect('pedidos:listaRecepcion')
    else:
        form = RecepcionForm()
        formset = ItemInsumoFormSet(instance=pedido)

        
    return render(request, 'pedidos/Recepcion-pedido.html', {
        'form': form,
        'formPedido': formpedido,
        'formset': formset,
        'pedido':pedido
    })

@login_required
@permission_required('pedidos.view_insumo', raise_exception=True)
def gestionarInsumos(request):
    nuevo_insumo = None
    insumos = Insumo.objects.filter(estado=True)

    if request.method == 'POST':
        insumo_form = InsumoForm(request.POST, request.FILES)
        if insumo_form.is_valid():

            descripcion = insumo_form.cleaned_data['descripcion'].lower()

            if Insumo.objects.filter(Q(descripcion__iexact=descripcion), estado=True).exists():
                messages.error(request, 'El Insumo ya existe')
                return render(request, 'pedidos/Gestion-insumos.html', {'insumo_form': insumo_form,'insumos':insumos})
            else:
                nuevo_insumo = insumo_form.save(commit=False)
                nuevo_insumo.save()
                messages.success(
                request,
                "Insumo agregado exitosamente")
                return redirect(reverse('pedidos:gestionarInsumos'))
                
    else:
        insumo_form = InsumoForm()
    return render(request, 'pedidos/Gestion-insumos.html', {'insumo_form': insumo_form,'insumos':insumos})

@login_required
@permission_required('pedidos.change_insumo', raise_exception=True)
def editarInsumos(request, pk):
    insumos= Insumo.objects.filter(estado=True)
    insumo = get_object_or_404(Insumo, pk=pk)
    if request.method == 'POST':
        form = InsumoForm(request.POST, request.FILES, instance=insumo)
        if form.is_valid():

            descripcion = form.cleaned_data['descripcion'].lower()

            existe_insumo = Insumo.objects.filter(
                Q(descripcion__iexact=descripcion)
            , estado=True).exclude(id=insumo.id).exists()

            if existe_insumo:
                messages.error(request, 'El insumo ya existe')
                return render(request, 'pedidos/editar-insumos.html', {'form': form, 'insumo': insumo, 'insumos':insumos})
            insumo = form.save()
            messages.success(request, "El producto ha sido modificado exitosamente.")
            print('Datos recibidos:', request.POST)
            return redirect('pedidos:gestionarInsumos')
        
        return render(request, 'pedidos/editar-insumos.html', {
                'form': form,
                'insumo': insumo,
                'insumos': insumos,
            })
    else:
        form = InsumoForm(instance=insumo)

    return render(request, 'pedidos/editar-insumos.html', {
        'form': form,
        'insumo': insumo,
        'insumos': insumos
    })

@login_required
@permission_required('pedidos.delete_insumo', raise_exception=True)
def eliminarInsumos(request, pk):
    insumo = get_object_or_404(Insumo, pk=pk)
    
    if request.method == 'POST':
        print("Estado anterior:", insumo.estado)
        insumo.estado = False
        insumo.save()
        messages.success(request, "El insumo ha sido eliminado exitosamente.")
        return redirect('pedidos:gestionarInsumos')
    
    else:
        messages.error(request, "La eliminación no se pudo completar.")
        return redirect('pedidos:gestionarInsumos') 


@login_required
@permission_required('pedidos.change_insumo', raise_exception=True)
def restarInsumos(request):
    insumos= Insumo.objects.filter(estado=True)
    if request.method == 'POST':
        formset = RestarInsumoFormSet(request.POST)

        if formset.is_valid():
           for form in formset:
                insumo = form.cleaned_data.get('insumo')
                cantidad_restar = form.cleaned_data.get('cantidad_restar')
                insumo.cantidad -= cantidad_restar
                if insumo.cantidad<0:
                    messages.error(request, "La cantidad retirada no debe ser mayor a la cantidad disponible.")
                    return redirect('pedidos:restar_insumos')
                else:
                    insumo.save()
                    form.save()
        
        messages.success(request, 'Cantidad retirada exitosamente.')
        return redirect('pedidos:restar_insumos')
                
    else:
        formset = RestarInsumoFormSet()

    return render(request, 'pedidos/Restar-insumos.html', {
    
        'formset': formset,
        'insumos':insumos
    })
 
@login_required
@permission_required('pedidos.view_insumo', raise_exception=True)
def informeInsumos(request):
    productos = Insumo.objects.filter(estado=True)

    # Ordenar por cantidad disponible (cantidad - cantidad_minima)
    orden = request.GET.get('orden')
    if orden == 'asc':
        productos = productos.order_by(Abs(F('cantidad') - F('cantidad_minima')))
    elif orden == 'desc':
        productos = productos.order_by(Abs(F('cantidad') - F('cantidad_minima'))).reverse()

    return render(request, 'pedidos/informe-insumos.html', {
        'productos': productos,
        'orden': orden
    })

apps/pedidos/templates/pedidos/Editar-insumos.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Gestión de Insumos</title>
        {% extends 'base.html' %}
        {% load static %}
        {% block css %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'css/pedidos/style-insumos.css' %}">
        <link rel="stylesheet" href="{% static 'css/pedidos/form.css' %}">
        <link rel="stylesheet" href="{% static 'css/pedidos/tabla.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        
        {% endblock %}
    </head>
    {% block content %}
    <body>

        <main id="main">
            {% if perms.pedidos.add_insumo and perms.pedidos.change_insumo and perms.pedidos.delete_insumo %}
            <form id="formulario" class="needs-validation formulario" method="post">
            {% csrf_token %}
                <div class="card-header navbar-dark" style="display: flex">
                    <h1 class="h3 mb-0 formulario__label"style="color: #ffffff">Insumo</h1>
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li class="{{ message.tags }} mensajes">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="form-container">
                    <div class="form-background">

                        <div class="formulario__grupo" id="grupo__descripcion">
                            <label for="desc_producto" class="formulario__label">Descripción del insumo</label>
                            <div class="formulario__grupo-input">
                                {{ form.descripcion}}
                                {% for error in form.descripcion.errors %}
                                    <div class="error"><p>Ingresa una descripcion válida</p></div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="formulario__grupo" id="grupo__precioProducto">
                            <label for="cant_producto" class="formulario__label">Cantidad disponible</label>
                            <div class="formulario__grupo-input">
                                {{ form.cantidad }}
                                {% for error in form.cantidad.errors %}
                                    <div class="error"><p>Ingresa una cantidad válida</p></div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="formulario__grupo" id="grupo__precioProducto">
                            <label for="cant_producto" class="formulario__label">Cantidad Minima</label>
                            <div class="formulario__grupo-input">
                                {{ form.cantidad_minima }}
                                {% for error in form.cantidad.errors %}
                                    <div class="error"><p>Ingresa una cantidad válida</p></div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="formulario__grupo" id="grupo__precioProducto">
                            <label for="cant_producto" class="formulario__label">Unidad de medida</label>
                            <div class="formulario__grupo-input">
                                {{ form.unidad_medida }}
                                {% for error in form.cantidad.errors %}
                                    <div class="error"><p>Ingresa una cantidad válida</p></div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="formulario__grupo formulario__grupo-btn-enviar">
                    <button type="submit" name="Editar" id="boton_editar" class="formulario__btn">
                    <i class="fa-solid fa-pen-to-square fa-sm me-2"></i>Editar
                    </button>
                </div>
            </form>

            <div class="table-container" id="tableContainer" >
                <div class="table-title">Lista de Insumos</div>
                <table>
                    <thead>
                        <tr>
                            <th>Descripción</th>
                            <th>Cantidad</th>
                            <th>Cantidad minima</th>
                            <th>Unidad Medida</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody class="tbody">
                        {% for insumo in insumos %}
                        <tr>
                            <td>{{ insumo.descripcion }}</td>
                            <td>{{ insumo.cantidad|floatformat:0 }}</td>
                            <td>{{ insumo.cantidad_minima|floatformat:0 }}</td>
                            <td>{{ insumo.unidad_medida }}</td>
                            {% if perms.pedidos.add_insumo and perms.pedidos.change_insumo and perms.pedidos.delete_insumo %}
                            <td class="action-item-list">
                                <button class="action-button edit-button"><a href="{% url 'pedidos:editar_insumos' insumo.id %}" style="color: white;">
                                    <i class="fas fa-edit" style="color: white;"></i></button>
                                    </a>
                                <form action="" id="formulario_eliminar" class="needs-validation formulario" method="post">
                                    {% csrf_token %}
                                    <button type="button" class="action-button delete-button" onclick="confirmCancel(`{% url 'pedidos:eliminar_insumos' insumo.id %}`)"><i class="fas fa-trash-alt" style="color: #ffffff;"></i></button>
                                </form>
                            </td>
                            {% endif %}       
       
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                    <tfoot>          
                        <tr class="total-row" id="foot-tr">
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tfoot> 
                </table>
            </div>
            {% endif %}

        </main>


        
        {% endblock %}

        {% block js %}
        <script src="{% static 'scripts/Validacion-ModificacionInsumos.js'%}"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        {% endblock %}
    </body>
</html>

apps/pedidos/templates/pedidos/Gestion-insumos.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Gestión de Insumos</title>
        {% extends 'base.html' %}
        {% load static %}
        {% block css %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/pedidos/style-insumos.css' %}">
        <link rel="stylesheet" href="{% static 'css/pedidos/form.css' %}">
        <link rel="stylesheet" href="{% static 'css/pedidos/tabla.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </head>
    {% block content %}
    <body>

        <main id="main">
            {% if perms.pedidos.add_insumo %}
            <form id="formulario" class="needs-validation formulario" method="post">
            {% csrf_token %}
                <div class="card-header navbar-dark" style="display: flex">
                    <h1 class="h3 mb-0 formulario__label"style="color: #ffffff">Insumo</h1>
                    {% if messages %}
                        <ul class="messages ">
                            {% for message in messages %}
                                <li class="formulario__grupo-correcto formulario__mensaje">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="form-container">
                    <div class="form-background">
                       
                        <div class="formulario__grupo" id="grupo__descripcion">
                            <label for="desc_producto" class="formulario__label">Descripción del insumo</label>
                            <div class="formulario__grupo-input">
                                {{ insumo_form.descripcion}}
                                <i class="formulario__validacion-estado fas fa-times-circle"></i>
                            </div>
                            <p class="formulario__input-error">Ingrese una descripcion correcta.</p>

                        </div>

                        <div class="formulario__grupo" id="grupo__cantidad">
                            <label for="cantidad" class="formulario__label">Cantidad disponible</label>
                            <div class="formulario__grupo-input">
                                {{ insumo_form.cantidad}}
                                <i class="formulario__validacion-estado fas fa-times-circle"></i>
                            </div>
                            <p class="formulario__input-error">Ingrese una cantidad valida.</p>
                        </div>
                        <div class="formulario__grupo" id="grupo__cantidad_minima">
                            <label for="cantidad_minima" class="formulario__label">Cantidad Minima</label>
                            <div class="formulario__grupo-input">
                                {{insumo_form.cantidad_minima}}
                                <i class="formulario__validacion-estado fas fa-times-circle"></i>
                            </div>
                            <p class="formulario__input-error">Ingrese una cantidad minima valida.</p>

                        </div>
                        <div class="formulario__grupo" id="grupo__unidadMedida">
                            <label for="unidadMedida" class="formulario__label">Unidad de medida</label>
                            <div class="formulario__grupo-input">
                                {{ insumo_form.unidad_medida }}
                            </div>
                        </div>
                        <div>
                            <div class="formulario__mensaje" id="formulario__mensaje">
                                <p><i class="fas fa-exclamation-triangle"></i><b>Error:</b>Rellena el formulario correctamente. </p>
                            </div>
                            <div class="formulario__mensaje-exito" id="formulario__mensaje-exito">
                                <p><i class="fas fa-exclamation-triangle"></i> Formulario enviado exitosamente!</p>
                            </div>
                        </div>
                    </div>
                    
                </div>

                <div class="formulario__grupo formulario__grupo-btn-enviar">
                    <button type="submit" name="Agregar" id="boton_agregar" class="formulario__btn"><i class="bi bi-send me-2"></i>Agregar</button>
                    </button>
                </div>
            </form>
            {% endif %}
            <div class="table-container" id="tableContainer">
                <div class="table-title">Lista de Insumos</div>

                <table>
                    <thead>
                        <tr>
                            <th>Descripción</th>
                            <th>Cantidad</th>
                            <th>Cantidad Minima</th>
                            <th>Unidad Medida</th>
                            {% if perms.pedidos.add_insumo and perms.pedidos.change_insumo and perms.pedidos.delete_insumo %}
                            <th>Acciones</th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody class="tbody">
                        {% for insumo in insumos %}
                        <tr>
                            <td>{{ insumo.descripcion }}</td>
                            <td>{{ insumo.cantidad|floatformat:0 }}</td>
                            <td>{{ insumo.cantidad_minima|floatformat:0 }}</td>
                            <td>{{ insumo.unidad_medida }}</td>
                            {% if perms.pedidos.add_insumo and perms.pedidos.change_insumo and perms.pedidos.delete_insumo %}
                            <td class="action-item-list">
                                <button class="action-button edit-button"><a href="{% url 'pedidos:editar_insumos' insumo.id %}" style="color: white;">
                                <i class="fas fa-edit" style="color: white;"></i></button>
                                </a>
                                <form action="" id="formulario_eliminar" class="needs-validation formulario" method="post">
                                    {% csrf_token %}
                                    <button type="button" class="action-button delete-button" onclick="confirmCancel(`{% url 'pedidos:eliminar_insumos' insumo.id %}`)"><i class="fas fa-trash-alt" style="color: #ffffff;"></i></button>
                                </form>
                            </td>
                            {% endif %}       
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                    <tfoot>          
                        <tr class="total-row" id="foot-tr">
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            {% if perms.pedidos.add_insumo and perms.pedidos.change_insumo and perms.pedidos.delete_insumo %}
                            <td></td>
                            {% endif %}
                        </tr>
                    </tfoot> 
                </table>
            </div>
            

        </main>
        {% endblock %}

        {% block js %}
        <script src="{% static 'scripts/Validacion-GestionInsumos.js'%}"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        {% endblock %}
    </body>
</html>