PanaderiaElMana/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('apps.usuarios.urls', namespace='usuarios')),
    path('pedidos/', include('apps.pedidos.urls', namespace='pedidos')),
    path('ventas/', include('apps.ventas.urls', namespace='ventas')),
    path('productos/', include('apps.productos.urls', namespace='productos')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pedidos/urls.py
from django.urls import path
from apps.pedidos import views 

app_name = 'pedidos'
urlpatterns = [
    path('', views.registroPedidos, name='registro_pedidos'),
    path('lista/',views.pedidos,name='lista_pedidos'),
    path('detalle/<int:pk>', views.editarPedidos, name='editarPedidos'),
    path('cancelar/<int:pk>', views.cancelarPedido, name='cancelarPedido'),
    path('lista_recepcion/',views.listaRecepcion,name='listaRecepcion'),
    path('recepcionar/<int:pk>', views.recepcionarPedidos, name='recepcionarPedidos'),
    path('insumos', views.gestionarInsumos, name='gestionarInsumos'),
    path('insumos/editar/<int:pk>', views.editarInsumos, name='editar_insumos'),
    path('insumos/eliminar/<int:pk>', views.eliminarInsumos, name='eliminar_insumos'),
    path('insumos/restar/', views.restarInsumos, name='restar_insumos'),
    path('informe', views.informeInsumos, name='informe_insumos'),
]

apps/productos/urls.py
from django.urls import path
from apps.productos import views 

app_name = 'productos'
urlpatterns = [
    path('', views.gestionarProductos, name='gestionarProductos'),
    path('baja_cantidad', views.productosCantidadBaja, name='baja_cantidad'),
    path('editar/<int:pk>', views.editarProductos, name='editar_productos'),
    path('eliminar/<int:pk>', views.eliminarProductos, name='eliminar_productos'),
    path('informe', views.informeProductos, name='informe_productos'),
]

apps/usuarios/urls.py
from django.urls import path
from apps.usuarios import views 

app_name = 'usuarios'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path("logout/", views.logout_view, name="logout"),
    path("home/", views.homeGestion, name="homeGestion")

]

apps/ventas/urls.py
from django.urls import path
from apps.ventas import views 

app_name = 'ventas'
urlpatterns = [
    path('', views.registroVentas, name='registro_ventas'),
    path('informe/', views.informeVentas, name="informe_ventas"),
    path('crearMayorista/', views.registroMayoristas, name="registro_mayoristas"),
    path("informe/<int:id>", views.detalleVenta, name="detalle_venta"),
    path("anular/<int:id>", views.anularVenta, name="anular_venta"),
    path("informe/mayoristas/", views.informeMayoristas, name="informe_mayoristas"),
    path("informe/mayoristas/darBaja/<int:cuit>", views.darDeBajaMayorista, name="baja_mayorista"),
    path("informe/mayoristas/<int:cuit>", views.modificarMayorista, name='modificar_mayorista'),
    path("informe/mayoristas/detalles/<int:cuit>", views.detallesMayorista, name="detalles_mayorista"),
    path('informe_ventas_pdf/', views.generar_informe_pdf, name='informe_ventas_pdf')
]

templates/Home.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>Panadería El Maná - Gestión de Procesos</title>
    <link rel="shortcut icon" href="{% static 'img/LogoPanaderia.png' %}"/>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
    
    <nav class="navbar navbar-expand-lg ">
        <div class="container fluid">
            <div class="sidebar-logo">
                <img src="{% static 'img/logoPanaderia.png' %}" alt="" width="85" height="85" id="logoMana">
                <a class="navbar-brand" href="#" ><h3>Panadería El Maná</h3></a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
               
            </div>
        </div>
    </nav>

    
    
    <main class="container my-4">
        <section class="tarjeta-mostrar text-center mb-5 " >
            <h1 class="display-4 mb-3 "><strong>Bienvenidos a Panadería El Maná</strong></h1>
            <p class="lead mb-4">Gestión integral de procesos para una panadería eficiente</p>
        </section>

        <section class="row mb-5">
        
            <div class="col-md-6 mb-4">
                <div class="card h-100 text-center text-bg-dark">
                    <div class="tarjeta-mostrar card-body ">
                        <h2 >Nuestra Misión</h2>
                        <p class="tarjeta-mostrar card-text">
                            En Panadería El Mana, nos dedicamos a optimizar cada aspecto de nuestro negocio, 
                            desde la compra de ingredientes hasta la venta de productos finales. 
                            Nuestro sistema de gestión centralizada nos permite tomar decisiones informadas 
                            y mejorar constantemente nuestra eficiencia.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="card h-100 text-center text-bg-dark">
                    <div class="tarjeta-mostrar card-body">
                        <h2>Características Principales</h2>
                        <ul class="tarjeta-mostrar list-unstyled">
                            <li>✓ Control de inventario en tiempo real</li>
                            <li>✓ Seguimiento de procesos de producción</li>
                            <li>✓ Gestión de ventas y pedidos</li>
                            <li>✓ Informes detallados y análisis</li>
                            <li>✓ Optimización de costos y recursos</li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>

        <section class="tarjeta-mostrar text-center mb-5">
            <h2 class="h3 mb-4">Explora Nuestro Sistema</h2>
            <a href="{% url 'usuarios:login' %}">
                <button class="btn btn-primary btn-lg" type="submit" >Comenzar Ahora</button>
            </a>
            
        </section>
    </main>

    <footer class=" py-3 mt-4 " data-bs-theme="dark">
        <div class="card-footer container text-center">
            <p class=" mb-0">&copy; 2023 Panadería El Mana. Todos los derechos reservados.</p>
        </div>
    </footer>

    <div class="video-container">
        <video src="{% static 'img/panaderiaVideo1080.mp4' %}" class="object-fit-cover" type="video/mp4" muted autoplay loop></video>
      </div>

    <div class="capa"></div>
      
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="shortcut icon" href="{% static 'img/LogoPanaderia.png' %}"/>
    <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet" />
    <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css %}
    {% endblock %}      
    
</head>
<body>
    <div class="wrapper">
        {% if user.is_authenticated %}
        <aside id="sidebar" class="no-informe">
            <div class="d-flex">
                <button class="toggle-btn" type="button" id="btnExpand">
                    <i class="lni lni-grid-alt" id="iconoExpand"></i>
                </button>
                
            </div>
            <div class="sidebar-logo">
                <img src="{% static 'img/logoPanaderia.png' %}" alt="" width="150" height="150" id="logoMana">
            </div>
            
            <ul class="sidebar-nav">
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link collapsed has-dropdown" 
                        aria-expanded="false" aria-controls="stock" data-collapsed = "true">
                        <i class="lni lni-package"></i>
                        <span>Stock</span>
                    </a>
                    <ul class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                        {% if perms.pedidos.add_insumo and perms.pedidos.change_insumo and perms.pedidos.delete_insumo or perms.pedidos.view_insumo%}
                        <li class="sidebar-item">
                            <a href="{% url 'pedidos:gestionarInsumos' %}" class="sidebar-link">Insumos</a>
                        </li>
                        {% endif %}
                        {% if perms.productos.add_producto or perms.productos.view_producto %}
                        <li class="sidebar-item">
                            <a href="{% url 'productos:gestionarProductos' %}" class="sidebar-link">Productos</a>
                        </li>
                        {% endif %}
                        {% if perms.pedidos.add_pedido %}
                        <li class="sidebar-item">
                            <a href="{% url 'pedidos:registro_pedidos' %}" class="sidebar-link">Pedido</a>
                        </li>
                        {% endif %}
                        {% if perms.pedidos.change_pedido and perms.pedidos.delete_pedido or perms.pedidos.view_pedido%}
                        <li class="sidebar-item">
                            <a href="{% url 'pedidos:lista_pedidos' %}"  class="sidebar-link">Lista de Pedidos</a>
                        </li>
                        {% endif%}
                        {% if perms.pedidos.add_insumo and perms.pedidos.change_insumo and perms.pedidos.delete_insumo %}
                        <li class="sidebar-item">
                            <a href="{% url 'pedidos:restar_insumos' %}"  class="sidebar-link">Restar Insumos</a>
                        </li>
                        {% endif %}

                    </ul>
                   
                    
                    
                </li>

                {% if perms.ventas.add_venta %}
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link collapsed has-dropdown" 
                        aria-expanded="false" aria-controls="producto" data-collapsed = "true">
                        <i class="lni lni-cart"></i>
                        <span>Ventas</span>
                    </a>
      

                    <ul id="producto" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">

                        <li class="sidebar-item">
                            <a href="{% url 'ventas:registro_ventas' %}" class="sidebar-link">Registrar venta</a>
                        </li>
                       
                    </ul>
                </li>
                {% endif %}
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link collapsed has-dropdown" 
                        aria-expanded="false" aria-controls="informe" data-collapsed = "true">
                        <i class="lni lni-graph"></i>
                        <span>Informes</span>
                    </a>
                    <ul id="informe" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                        {% if perms.ventas.add_venta or perms.ventas.view_venta %}
                        <li class="sidebar-item">
                            <a href="{% url 'ventas:informe_ventas' %}" class="sidebar-link">Listado de Ventas</a>
                        </li>
                        {% endif %}

                        {% if perms.productos.view_producto %}
                        <li class="sidebar-item">
                            <a href="{% url 'productos:informe_productos' %}" class="sidebar-link">Listado de productos</a>
                        </li>
                        {% endif %}
                        
                        {% if perms.pedidos.view_insumo %}
                        <li class="sidebar-item">
                            <a href="{% url 'pedidos:informe_insumos' %}" class="sidebar-link">Materia prima faltante</a>
                        </li>
                        {% endif %}

                        {% if perms.pedidos.view_recepcionpedidos %}
                        <li class="sidebar-item">
                            <a href="{% url 'pedidos:listaRecepcion' %}" class="sidebar-link">Recepcion de pedidos</a>
                        </li>
                        {% endif %}
                        {% if perms.ventas.view_mayorista %}
                        <li class="sidebar-item">
                            <a href="/ventas/informe/mayoristas" class="sidebar-link">Listado de Mayoristas</a>
                        </li>
                        {% endif %}
                        
                    </ul>
                </li>
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link collapsed has-dropdown" 
                        aria-expanded="false" aria-controls="administracion" data-collapsed = "true">
                        <i class="lni lni-cog"></i>
                        <span>Administración</span>
                    </a>
                    <ul id="administracion" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                        
                        <li class="sidebar-item">
                            {% if user.is_superuser %}
                            <a href="/admin/" class="sidebar-link">Panel de administrador</a>
                            {% endif %}
                        </li>
                        <li class="sidebar-item">
                            {% if perms.ventas.add_mayorista %}
                            <a href="{% url 'ventas:registro_mayoristas' %}" class="sidebar-link">Registrar mayorista</a>
                            {% endif %}

                        </li>
                       
                    </ul>
                </li>
              
                <li class="sidebar-item">
                    <a href="#" class="sidebar-link collapsed has-dropdown" 
                        aria-expanded="false" aria-controls="notificacion" data-collapsed = "true">
                        <i class="fa-regular fa-bell" id="iconoNotificacion"></i>
                        <span>Notificaciones</span>
                    </a>
                    <ul id="notificacion" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                       
                    </ul>
                </li>               
            </ul>
            <div class="sidebar-footer">
                <a href="#" class="sidebar-link"> 
                    <span>Usuario: {{ user.username }}</span>
                   
                </a>
            </div>
            <div class="sidebar-footer">
                <a href="{% url 'usuarios:logout' %}" class="sidebar-link"> 
                    <i class="lni lni-exit"></i>
                    <span>Logout</span>
                </a>
            </div>
        </aside>
        <div class="main p-3">
            <div>
                {% block content %}
                {% endblock %}            
            </div>
        </div>
        {% else %}
        {% endif %}
        
    </div>
    
    <footer class="py-1 mt-8 fixed-bottom">
        <div class="card-footer container text-center">
            <p class=" mb-0">&copy; 2024 Panadería El Mana. Todos los derechos reservados.</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
    <script src="{% static 'scripts/base.js' %}"></script>
    {% block js %} {% endblock %}
</body>
</html>